[project]
name = "monthly-expense"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "reportlab>=4.4.4",
    "streamlit>=1.51.0",
]
